using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace OperationPro
{
    public partial class FrmStaff : DevExpress.XtraEditors.XtraForm
    {
        public FrmStaff()
        {
            InitializeComponent();
            LoadMainList();
        }

        public void LoadMainList()
        {
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            OperationPro.OperationProEntities dbContext = new OperationPro.OperationProEntities();
            // Call the Load method to get the data for the given DbSet from the database.
            dbContext.TBL_MainMaster.Load();
            // This line of code is generated by Data Source Configuration Wizard
            gridControl1.DataSource = dbContext.TBL_MainMaster.Select(s => new { s.ID, s.EmpName, s.EMPID, s.TGID, s.Email, s.Mobile, s.IqamaID, s.IqamaExpDate, s.SARID, s.SARExpDate, s.Passport, s.PassportExpDate, s.TBL_Company.Company, s.TBL_Department.Department, s.TBL_JOB.JobTitle, s.TBL_Location.Location }).ToList();
        }
        private void barclose_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            Close();
        }

        private void barnew_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            FrmStaffNewEdit frmstaffnew = new FrmStaffNewEdit(1);
            frmstaffnew.MdiParent = this.MdiParent;
            frmstaffnew.Show();
        }

        private void baredit_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            int tRcvrLineID = int.Parse(cardView1.GetFocusedRowCellValue("ID").ToString());

            FrmStaffNewEdit frmstaffnew = new FrmStaffNewEdit(2, tRcvrLineID);
            frmstaffnew.MdiParent = this.MdiParent;
            frmstaffnew.Show();
        }

        private void barrefresh_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            LoadMainList();
        }

        private void bardel_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            if(MessageBox.Show("Do you want to delete Staff Details?", "Warning",MessageBoxButtons.OKCancel) == DialogResult.OK)
            {
                int tRcvrLineID = int.Parse(cardView1.GetFocusedRowCellValue("ID").ToString());

                OperationPro.OperationProEntities opro = new OperationProEntities();
                TBL_PdfFile tbPdf = opro.TBL_PdfFile.Where(s => s.MasterID == tRcvrLineID && s.DOCID == 1).First();
                if (tbPdf != null)
                {
                    opro.TBL_PdfFile.Remove(tbPdf);
                    opro.SaveChanges();
                }
                tbPdf = opro.TBL_PdfFile.Where(s => s.MasterID == tRcvrLineID && s.DOCID == 2).First();
                if (tbPdf != null)
                {
                    opro.TBL_PdfFile.Remove(tbPdf);
                    opro.SaveChanges();
                }
                tbPdf = opro.TBL_PdfFile.Where(s => s.MasterID == tRcvrLineID && s.DOCID == 3).First();
                if (tbPdf != null)
                {
                    opro.TBL_PdfFile.Remove(tbPdf);
                    opro.SaveChanges();
                }

                TBL_MainMaster tb = opro.TBL_MainMaster.Where(s => s.ID == tRcvrLineID).First();
                opro.TBL_MainMaster.Remove(tb);
                opro.SaveChanges();
                
                LoadMainList();

            }
        }
    }
}