//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationPro
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class OperationProEntities : DbContext
    {
        public OperationProEntities()
            : base("name=OperationProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Company> TBL_Company { get; set; }
        public virtual DbSet<TBL_Department> TBL_Department { get; set; }
        public virtual DbSet<TBL_Document> TBL_Document { get; set; }
        public virtual DbSet<TBL_JOB> TBL_JOB { get; set; }
        public virtual DbSet<TBL_Location> TBL_Location { get; set; }
        public virtual DbSet<TBL_MainMaster> TBL_MainMaster { get; set; }
        public virtual DbSet<TBL_PdfFile> TBL_PdfFile { get; set; }
        public virtual DbSet<TBL_Type> TBL_Type { get; set; }
        public virtual DbSet<TBL_UserMaster> TBL_UserMaster { get; set; }
        public virtual DbSet<TBL_Vehicle> TBL_Vehicle { get; set; }
        public virtual DbSet<TBL_WarningDays> TBL_WarningDays { get; set; }
    
        public virtual ObjectResult<SP_Warning1_Result> SP_Warning()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_Warning1_Result>("SP_Warning1");
        }
    
       
    }
}
