//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MainMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_MainMaster()
        {
            this.TBL_PdfFile = new HashSet<TBL_PdfFile>();
            this.TBL_Vehicle = new HashSet<TBL_Vehicle>();
        }
    
        public int ID { get; set; }
        public string EmpName { get; set; }
        public string EMPID { get; set; }
        public string TGID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> JobTitle { get; set; }
        public Nullable<int> Depart { get; set; }
        public Nullable<int> Location { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string IqamaID { get; set; }
        public Nullable<System.DateTime> IqamaExpDate { get; set; }
        public string SARID { get; set; }
        public Nullable<System.DateTime> SARExpDate { get; set; }
        public string Passport { get; set; }
        public Nullable<System.DateTime> PassportExpDate { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual TBL_Company TBL_Company { get; set; }
        public virtual TBL_Department TBL_Department { get; set; }
        public virtual TBL_JOB TBL_JOB { get; set; }
        public virtual TBL_Location TBL_Location { get; set; }
        public virtual TBL_MainMaster TBL_MainMaster1 { get; set; }
        public virtual TBL_MainMaster TBL_MainMaster2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_PdfFile> TBL_PdfFile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Vehicle> TBL_Vehicle { get; set; }
    }
}
