//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Vehicle
    {
        public int ID { get; set; }
        public string Vehicle { get; set; }
        public Nullable<System.DateTime> VehicleExpDate { get; set; }
        public Nullable<System.DateTime> InsuranceExpDate { get; set; }
        public Nullable<System.DateTime> AuthorizationExpDate { get; set; }
        public string Model { get; set; }
        public Nullable<int> Type { get; set; }
        public string plateNo { get; set; }
        public Nullable<int> AuthorizationID { get; set; }
        public byte[] PDFFile { get; set; }
    
        public virtual TBL_MainMaster TBL_MainMaster { get; set; }
        public virtual TBL_Type TBL_Type { get; set; }
    }
}
