//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PdfFile
    {
        public int ID { get; set; }
        public Nullable<int> DOCID { get; set; }
        public Nullable<int> MasterID { get; set; }
        public byte[] PDFFile { get; set; }
    
        public virtual TBL_Document TBL_Document { get; set; }
        public virtual TBL_MainMaster TBL_MainMaster { get; set; }
        public virtual TBL_PdfFile TBL_PdfFile1 { get; set; }
        public virtual TBL_PdfFile TBL_PdfFile2 { get; set; }
    }
}
