//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OperationPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WarningDays
    {
        public int ID { get; set; }
        public Nullable<int> IqamaExpWarnDay { get; set; }
        public Nullable<int> SarExpWarnDay { get; set; }
        public Nullable<int> PassportExpWarnDay { get; set; }
        public Nullable<int> VehicleWarnDay { get; set; }
        public Nullable<int> InsuranceWarnDay { get; set; }
        public Nullable<int> AuthorizationWarnDay { get; set; }
    }
}
